services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432:${DATABASE_PORT}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_URL}']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres:
